language: node_js
  - "8"

before_script:
  - cd client/
  - npm install && cd ..
  - npm install -g ganache-cli
  - npm install -g truffle@5.0.0

script:
  - ganache-cli &
  - sleep 5
  - truffle test
